In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print a

[1 2 3]


In [4]:
print type(a)

<type 'numpy.ndarray'>


In [5]:
b = a * 2
print b

[2 4 6]


In [7]:
print 2 * a + b

[ 4  8 12]


In [8]:
print np.exp(a)

[  2.71828183   7.3890561   20.08553692]


In [9]:
print np.log(a)

[ 0.          0.69314718  1.09861229]


In [10]:
print np.log(np.exp(a))

[ 1.  2.  3.]


In [11]:
print np.sin(a)

[ 0.84147098  0.90929743  0.14112001]


In [12]:
print np.sin(np.pi/2)

1.0


In [13]:
print np.pi

3.14159265359


In [14]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print a

[[1 2 3]
 [4 5 6]]


In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = np.array([[[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]],[[5, 6, 7, 8],[5, 6, 7, 8],[5, 6, 7, 8]]])
print a

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]]]


In [17]:
print a.ndim

3


In [18]:
print a.shape

(2L, 3L, 4L)


In [20]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print b

[[1 2 3]
 [4 5 6]]


In [21]:
print b[0,2]

3


In [22]:
print b[-1, -1]

6


In [23]:
print b[0, :]

[1 2 3]


In [24]:
print b[:, 0]

[1 4]


In [25]:
print b[:,1:]

[[2 3]
 [5 6]]


In [26]:
print b[:2, :2]

[[1 2]
 [4 5]]


In [28]:
m = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
print m

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
print m[1,2]

7


In [30]:
print m[-1, -1]

14


In [31]:
print m[1, 1:3]

[6 7]


In [32]:
print m[1:, 2]

[ 7 12]


In [33]:
print m[:2, 3:]

[[3 4]
 [8 9]]


In [34]:
a = np.array([1, 2, 3, 4])
idx = np.array([True, False, True, False])
print a[idx]

[1 3]


In [35]:
print a[a % 2 != 0]

[1 3]


In [37]:
print a[0, 0, 1, 0]

IndexError: too many indices for array