In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
print x.dtype

int32


In [4]:
print np.inf

inf


In [5]:
print np.exp(-np.inf)

0.0


In [9]:
a = np.array([np.inf])
print a.dtype

float64


In [10]:
a = np.zeros(5)
print a

[ 0.  0.  0.  0.  0.]


In [11]:
a = np.ones(5)
print a

[ 1.  1.  1.  1.  1.]


In [13]:
a = np.zeros((5, 2), dtype ='f8')

print a

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [28]:
c = np.zeros(5, dtype = 'S')
c[0] = 'abxx'
c[1] = 'aaaaaaa'
print c

['a' 'a' '' '' '']


In [19]:
a = np.ones(5)
print a.dtype

float64


In [20]:
d = np.ones((2, 3, 4), dtype = 'i8')
print d

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [21]:
e = range(10)
print e

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
f = np.ones_like(e)
print f

[1 1 1 1 1 1 1 1 1 1]


In [23]:
print f.dtype

int32


In [24]:
f = np.ones(8)
print f.dtype

float64


In [29]:
g = np.empty((4, 3))
print g

[[  1.04741917e-321   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]


In [30]:
a = np.arange(10)
print a

[0 1 2 3 4 5 6 7 8 9]


In [31]:
b = np.arange(3, 21, 2)
print b

[ 3  5  7  9 11 13 15 17 19]


In [32]:
c = np.linspace(3, 21, 5)
print c

[  3.    7.5  12.   16.5  21. ]


In [35]:
d = np.logspace(0, 3, 4)
print d

[    1.    10.   100.  1000.]


In [37]:
np.random.seed(0)
a = np.random.rand(10)
print a

[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
  0.43758721  0.891773    0.96366276  0.38344152]


In [38]:
b = np.random.randn(10)
print b

[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [40]:
c = np.random.rand(2, 3)
print c

[[ 0.14335329  0.94466892  0.52184832]
 [ 0.41466194  0.26455561  0.77423369]]


In [43]:
a = np.zeros((2, 3))

In [51]:
a = np.arange(1,13)
print a

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [52]:
b = a.reshape(3, 4)
print b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
b = a.reshape(2, -1)
print b

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [54]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
print b

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [56]:
c = b.flatten()
print c

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [60]:
x = np.arange(5)
#x = np.array([1, 2, 3, 4, 5])
b = x[:, np.newaxis]

print b

[[0]
 [1]
 [2]
 [3]
 [4]]


In [70]:
a = np.ones((2, 3))
b = np.zeros((2, 3))

In [71]:
c = np.hstack([a, b])
print c

[[ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]]


In [72]:
d = np.vstack([a, b])
print d

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [73]:
c = np.dstack([a, b])
print c

[[[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]

 [[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]]


In [74]:
d = np.stack([a, b])
print d

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [75]:
print np.array_equal(d[0, :, :], a)

True


In [76]:
e = np.stack([a, b], axis=1)
print e

[[[ 1.  1.  1.]
  [ 0.  0.  0.]]

 [[ 1.  1.  1.]
  [ 0.  0.  0.]]]


In [77]:
e = np.r_[a, b]
print e

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [84]:
e = np.c_[np.array([[1,2,3],[1, 2,3]]), np.array([[4, 5, 6],[2, 3, 4]])]
print e

[[1 2 3 4 5 6]
 [1 2 3 2 3 4]]


In [85]:
e = np.r_[np.array([[1,2,3],[1, 2,3]]), np.array([[4, 5, 6],[2, 3, 4]])]
print e

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [2 3 4]]


In [86]:
e = np.r_[np.array([[1,2,3]]), np.array([[4, 5, 6]])]
print e

[[1 2 3]
 [4 5 6]]


In [87]:
e = np.r_[np.array([1,2,3]), np.array([4, 5, 6])]
print e

[1 2 3 4 5 6]


In [89]:
e = np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]
print e

[[1 4]
 [2 5]
 [3 6]]


In [90]:
e = np.c_[np.array([[1, 2, 3]]), np.array([[4, 5, 6]])]
print e

[[1 2 3 4 5 6]]


In [92]:
a = np.array([1, 2, 3])
b = np.tile(a, 2)
c = np.tile(a, (3, 2))
print c

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [93]:
x = np.arange(3)
y = np.arange(5)
X, Y = np.meshgrid(x, y)
print X
print Y

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [94]:
print zip(X, Y)

[(array([0, 1, 2]), array([0, 0, 0])), (array([0, 1, 2]), array([1, 1, 1])), (array([0, 1, 2]), array([2, 2, 2])), (array([0, 1, 2]), array([3, 3, 3])), (array([0, 1, 2]), array([4, 4, 4]))]


In [95]:
print [zip(x, y) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)], [(0, 1), (1, 1), (2, 1)], [(0, 2), (1, 2), (2, 2)], [(0, 3), (1, 3), (2, 3)], [(0, 4), (1, 4), (2, 4)]]


In [96]:
print [x for x, y in zip(X, Y)]

[array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2]), array([0, 1, 2])]


In [101]:
import matplotlib.pylab as plt
plt.scatter(X, Y, linewidths = 10)
plt.show()