In [2]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 3, 2, 4])

In [8]:
print a == b

[ True False False  True]


In [9]:
print np.all(a == b)

False


In [10]:
a = np.array([1, 10, 100])
b = np.log(a)
print b
c = np.log10(a)
print c

[ 0.          2.30258509  4.60517019]
[ 0.  1.  2.]


In [11]:
d = a + 1
print d

[  2  11 101]


In [12]:
e = np.tile(np.arange(0, 40, 10), (3, 1))
print e

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [13]:
print e.T

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [14]:
x = np.array([0, 1, 2])

In [16]:
print e.T + x

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [17]:
a = np.arange(0, 10, 3)[:, np.newaxis]
print a

[[0]
 [3]
 [6]
 [9]]


In [19]:
print a + x

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
print e + x

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [23]:
x = np.array([1, 2, 3, 4])
print np.sum(x)

10


In [24]:
x1 = [1, 2, 3, 4]
x1.sum()

AttributeError: 'list' object has no attribute 'sum'

In [25]:
x.sum()

10

In [26]:
print x.min()

1


In [27]:
print x.max()

4


In [28]:
print x.argmin()

0


In [29]:
print x.argmax()

3


In [30]:
print x.mean()

2.5


In [32]:
print np.median(x)

2.5


In [33]:
a = np.zeros((100, 100), dtype ='i8')
print a

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [34]:
print np.any(a != 0)

False


In [35]:
print np.all(a == 0)

True


In [36]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [41]:
print ((a <= b) & (b <=c)).all()

True


In [42]:
x = np.array([[1, 2],[3, 4]])

In [43]:
x.sum()

10

In [44]:
print x.sum(axis=0)

[4 6]


In [45]:
print x.sum(axis=1)

[3 7]


In [58]:
a = np.array([[1,2,3,1,2,3,],[2,3,4,2,3,4],[3,4,5,3,4,5],[4,5,6,4,5,6],[6,7,8,6,7,8]])

In [59]:
print a

[[1 2 3 1 2 3]
 [2 3 4 2 3 4]
 [3 4 5 3 4 5]
 [4 5 6 4 5 6]
 [6 7 8 6 7 8]]


In [48]:
print a.max()

8


In [60]:
b = a.max()
print b

8


In [61]:
print a.sum(axis=1)

[12 18 24 30 42]


In [62]:
print a.mean()

4.2


In [63]:
print a.mean(axis=0)

[ 3.2  4.2  5.2  3.2  4.2  5.2]


In [64]:
a = np.array([[1,9,2],[2,6,3]])
print a

[[1 9 2]
 [2 6 3]]


In [65]:
b = np.sort(a, axis = 0)
print b

[[1 6 2]
 [2 9 3]]


In [66]:
b = np.sort(a, axis = 1)
print b

[[1 2 9]
 [2 3 6]]


In [67]:
b = a.sort(axis = 0)
print b

None


In [68]:
print a

[[1 6 2]
 [2 9 3]]


In [69]:
a = np.array([1, 4,2,6])
print np.argsort(a)

[0 2 1 3]


In [77]:
a = np.array([[1,2,3,1,2,3,],[2,3,4,2,3,4],[3,4,5,3,4,5],[4,5,6,4,5,6],[1,7,8,6,7,8]])
print a

[[1 2 3 1 2 3]
 [2 3 4 2 3 4]
 [3 4 5 3 4 5]
 [4 5 6 4 5 6]
 [1 7 8 6 7 8]]


In [78]:
b = np.argsort(a[:, 0])
print b

[0 4 1 2 3]
