In [1]:
import numpy as np

In [2]:
x = np.array([[1], [2]])
print x

[[1]
 [2]]


In [3]:
x = np.diag([1, 2, 3])
print x

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [5]:
x = np.identity(3)
print x

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
x = np.eye(3)
print x

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [8]:
print x + y

[5 7 9]


In [9]:
print x * y

[ 4 10 18]


In [10]:
print np.dot(x, y)

32


In [11]:
print np.dot(x.T, y)

32


In [12]:
print np.mean(x)

2.0


In [17]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[1, 2],[3, 4],[5, 6]])

In [18]:
print np.dot(A, B)

[[22 28]
 [49 64]]


In [21]:
I = np.eye(3)

In [22]:
print np.dot(A, I)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [23]:
from sklearn.datasets import make_regression
X, y = make_regression(4, 3)

In [24]:
print X
print y

[[-0.11550332 -1.73730359  0.64206976]
 [ 0.27798903  0.73951018 -0.94159262]
 [-0.3013568   0.66884661 -0.71321884]
 [ 1.15274181 -0.43239584 -0.96986394]]
[-29.56081541 -29.8349784  -21.52113926 -73.8375516 ]


In [25]:
w = np.linalg.lstsq(X, y)[0]
print w

[  6.57247856  40.86827961  65.72328923]


In [26]:
e = y - np.dot(w, X.T)
print e

[  1.42108547e-14  -7.10542736e-15  -2.13162821e-14   1.42108547e-14]


In [29]:
e = y - np.dot(X, w.T)

print e

[  1.42108547e-14  -7.10542736e-15  -2.13162821e-14   1.42108547e-14]


In [30]:
e = y - np.dot(w.T, X.T)

print e

[  1.42108547e-14  -7.10542736e-15  -2.13162821e-14   1.42108547e-14]


In [31]:
e = y - np.dot(X, w)

print e

[  1.42108547e-14  -7.10542736e-15  -2.13162821e-14   1.42108547e-14]


In [46]:
x = np.array([1, 2, 3])
A = np.arange(1, 10).reshape(3,3)

In [41]:
np.dot(x, A, x)

array([  5173,  16264, 119232])

In [47]:
np.dot(np.dot(x, A), x)

228

In [48]:
np.dot(x, np.dot(A, x))

228