In [2]:
import numpy as np

In [15]:
A = np.array([[1, 3, -2],[3, 5, 6],[2, 4, 3]])

In [16]:
b = np.array([[5],[7],[8]])

In [10]:
Ainv = np.linalg.inv(A)
print Ainv

[[ 2.25  4.25 -7.  ]
 [-0.75 -1.75  3.  ]
 [-0.5  -0.5   1.  ]]


In [19]:
x = np.dot(Ainv, b)
print x

[[-15.]
 [  8.]
 [  2.]]


In [20]:
print np.dot(A, x) - b

[[ -3.55271368e-15]
 [ -1.77635684e-14]
 [ -1.24344979e-14]]


In [21]:
x, resid, rank, s = np.linalg.lstsq(A, b)
print x, resid, rank, s

[[-15.]
 [  8.]
 [  2.]] [] 3 [ 9.95351327  3.73041127  0.10772757]


In [22]:
print np.dot(A, x) - b

[[ -3.55271368e-15]
 [ -3.55271368e-15]
 [ -1.77635684e-15]]


In [48]:
A = np.array([[1, 2, 3],[4, 5, 6]])

In [49]:
b = np.array([[1],[2]])

In [50]:
print np.linalg.lstsq(A, b)

(array([[-0.05555556],
       [ 0.11111111],
       [ 0.27777778]]), array([], dtype=float64), 2, array([ 9.508032  ,  0.77286964]))


In [51]:
Apinv =np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)
print Apinv

[[ 0.  4.]
 [ 2.  0.]
 [ 0.  1.]]


In [52]:
print np.linalg.inv(np.dot(A.T, A))
print np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)

[[  1.50119988e+15  -3.00239975e+15   1.50119988e+15]
 [ -3.00239975e+15   6.00479950e+15  -3.00239975e+15]
 [  1.50119988e+15  -3.00239975e+15   1.50119988e+15]]
[[ 0.  4.]
 [ 2.  0.]
 [ 0.  1.]]


In [57]:
print np.dot(A.T, A)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [53]:
x = np.dot(Apinv, b)
print x

[[ 8.]
 [ 2.]
 [ 2.]]


In [54]:
print np.dot(A, x) - b

[[ 17.]
 [ 52.]]


In [55]:
x, resid, rank, s = np.linalg.lstsq(A, b)

In [56]:
print np.dot(A, x) - b

[[  4.44089210e-16]
 [  0.00000000e+00]]
